baseURL = "https://ipolyzos.com"
title   = "Ioannis Polyzos"
theme   = "apple"

defaultContentLanguage = "en"
languageName           = "English"
isoCode                = "en"

enableRobotsTXT = true
paginate        = 15
summaryLength   = 0
buildDrafts     = false
buildFuture     = false
buildExpired    = false

[outputs]
  home = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true
