languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

# title = "Ioannis Polyzos"
# logo = "logo.jpg"
description = "Personal website of Ioannis Polyzos"
copyright = "© Ioannis Polyzos. All rights reserved."

dateFormat = "2 January 2006"
