[[main]]
  name = "home"
  pageRef = "/"
  weight = 1
[[main]]
  name = "about"
  pageRef = "about"
  weight = 10
[[main]]
  name = "cv"
  pageRef = "cv"
  weight = 20
[[main]]
  name = "projects"
  pageRef = "projects"
  weight = 30
[[main]]
  name = "publications"
  pageRef = "publications"
  weight = 40