[[main]]
name = "About"
pageRef = "about"
weight = 10
[[main]]
name = "CV"
url = "https://linkedin.com/in/ipolyzos"
weight = 20
[[main]]
name = "Projects"
pageRef = "projects"
weight = 30
[[main]]
name = "Publications"
pageRef = "publications"
weight = 40
