[[main]]
name = "home"
pageRef = "/"
weight = 1
[[main]]
name = "about"
pageRef = "about"
weight = 10
[[main]]
name = "cv"
url = "https://linkedin.com/in/ipolyzos"
weight = 20
[[main]]
name = "projects"
pageRef = "projects"
weight = 30
[[main]]
name = "publications"
pageRef = "publications"
weight = 40
