name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add manual trigger

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"

      - name: Build website
        run: hugo --minify

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: website
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: ipolyzos/ipolyzos.com
          publish_dir: ./public
